sudo: required
services:
  - docker
  
before_install:
  - docker build -t michael-gattas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true michael-gattas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-724772051426"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY